GET http://localhost:1337/api/v1/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImVkZGllIiwidXNlcklkIjoxLCJpYXQiOjE2MTgxMjk4NTksImV4cCI6MTYxODEzMTA1OX0.bjbkZfe3QRTwM3Why6e0pg8BUU9xsqPEG_DJ_FmeVAM

### 查看 

POST http://localhost:1337/api/v1/posts/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IndpbmR5IiwiaWF0IjoxNjE4MTI2NDE0fQ.xhKJta_AKgxeAr-bNLuwujRnxAW6vU3oGn0l8QKrmcM"
}

### 重取token
DELETE http://localhost:1337/api/v1/posts/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IndpbmR5IiwiaWF0IjoxNjE4MTI2NDE0fQ.xhKJta_AKgxeAr-bNLuwujRnxAW6vU3oGn0l8QKrmcM"
}
### 登出
POST http://localhost:1337/api/v1/posts/login
Content-Type: application/json

{
  "userName": "eddie",
  "password": "123"
}