GET http://localhost:3000/api/v1/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IndpbmR5IiwidXNlcklkIjozLCJ1c2VyQXV0aCI6IjMiLCJpYXQiOjE2MTgzMDQ5OTMsImV4cCI6MTYxODMwNjE5M30.JRjMgKCcDbk11z4JKJgKjSid2OzucJoB2ulcRp3O5uk

### 查看 

POST http://localhost:3000/api/v1/posts/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IndpbmR5IiwiaWF0IjoxNjE4MTI2NDE0fQ.xhKJta_AKgxeAr-bNLuwujRnxAW6vU3oGn0l8QKrmcM"
}

### 重取token
DELETE http://localhost:3000/api/v1/posts/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IndpbmR5IiwiaWF0IjoxNjE4MTI2NDE0fQ.xhKJta_AKgxeAr-bNLuwujRnxAW6vU3oGn0l8QKrmcM"
}
### 登入
POST http://localhost:3000/api/v1/posts/login
Content-Type: application/json

{
  "userName": "windy",
  "password": "456"
}